(autoload 'htmlize-protect-string               "htmlize" "" nil)
(autoload 'htmlize-buffer-substring-no-invisible "htmlize" "" nil)
(autoload 'htmlize-trim-ellipsis                "htmlize" "" nil)
(autoload 'htmlize-untabify                     "htmlize" "" nil)
(autoload 'htmlize-despam-address               "htmlize" "" nil)
(autoload 'htmlize-make-hyperlinks              "htmlize" "" nil)
(autoload 'htmlize-defang-local-variables       "htmlize" "" nil)
(autoload 'htmlize-get-color-rgb-hash           "htmlize" "" nil)
(autoload 'htmlize-face-specifies-property      "htmlize" "" nil)
(autoload 'htmlize-face-color-internal          "htmlize" "" nil)
(autoload 'htmlize-face-foreground              "htmlize" "" nil)
(autoload 'htmlize-face-background              "htmlize" "" nil)
(autoload 'htmlize-color-to-rgb                 "htmlize" "" nil)
(autoload 'htmlize-face-emacs21-attr            "htmlize" "" nil)
(autoload 'htmlize-face-size                    "htmlize" "" nil)
(autoload 'htmlize-face-to-fstruct              "htmlize" "" nil)
(autoload 'htmlize-copy-attr-if-set             "htmlize" "" nil 'macro)
(autoload 'htmlize-merge-size                   "htmlize" "" nil)
(autoload 'htmlize-merge-two-faces              "htmlize" "" nil)
(autoload 'htmlize-merge-faces                  "htmlize" "" nil)
(autoload 'htmlize-attrlist-to-fstruct          "htmlize" "" nil)
(autoload 'htmlize-face-list-p                  "htmlize" "" nil)
(autoload 'htmlize-make-face-map                "htmlize" "" nil)
(autoload 'htmlize-unstringify-face             "htmlize" "" nil)
(autoload 'htmlize-faces-in-buffer              "htmlize" "" nil)
(autoload 'htmlize-method                       "htmlize" "" nil 'macro)
(autoload 'htmlize-method-function              "htmlize" "" nil)
(autoload 'htmlize-memoize                      "htmlize" "" nil 'macro)
(autoload 'htmlize-default-doctype              "htmlize" "" nil)
(autoload 'htmlize-default-body-tag             "htmlize" "" nil)
(autoload 'htmlize-css-specs                    "htmlize" "" nil)
(autoload 'htmlize-css-insert-head              "htmlize" "" nil)
(autoload 'htmlize-css-insert-text              "htmlize" "" nil)
(autoload 'htmlize-inline-css-body-tag          "htmlize" "" nil)
(autoload 'htmlize-inline-css-insert-text       "htmlize" "" nil)
(autoload 'htmlize-font-body-tag                "htmlize" "" nil)
(autoload 'htmlize-font-insert-text             "htmlize" "" nil)
(autoload 'htmlize-buffer-1                     "htmlize" "" nil)
(autoload 'htmlize-with-fontify-message         "htmlize" "" nil 'macro)
(autoload 'htmlize-ensure-fontified             "htmlize" "" nil)
(autoload 'htmlize-buffer                       "htmlize" "" t)
(autoload 'htmlize-region                       "htmlize" "" t)
(autoload 'htmlize-region-for-paste             "htmlize" "" nil)
(autoload 'htmlize-make-file-name               "htmlize" "" nil)
(autoload 'htmlize-file                         "htmlize" "" t)
(autoload 'htmlize-many-files                   "htmlize" "" t)
(autoload 'htmlize-many-files-dired             "htmlize" "" t)
(provide 'htmlize-epackage-autoloads)
